- hosts: all
  become: yes
  tasks: 
     - name: create new deployment1
       command: "{{ bin_dir }}/kubectl apply -f /home/ec2-user/Deployment.yml"
     - name: create new service
       command: "{{ bin_dir }}/kubectl apply -f /home/ec2-user/Service.yml"
