kind: Deployment
apiVersion: apps/v1
metadata:
   name: mrdevops
spec:
   replicas: 4
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: mrdevops
   template:
      metadata:
        labels:
          app: mrdevops
      spec:
       containers:
        - name: mrdevops
          image: 463423328685.dkr.ecr.us-east-1.amazonaws.com/hga_hv_pocss 
          imagePullPolicy: Always
          ports:
          - containerPort: 80
